---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install basic utilities
    package:
      name: 
        - htop
        - tmux
        - cowsay
        - cmatrix
        - fortune-mod
        - vim
      